version: "2"
linters:
  disable:
    - lll
    - varnamelen
    - wrapcheck
    - err113
    - gochecknoglobals
    - exhaustruct
    - cyclop
    - funlen
    - gocognit
    - gocyclo
    - testpackage
    - depguard
    - mnd
    - maintidx

  settings:
    tagliatelle:
      case:
        rules:
          json: snake
